[workspace]

members = [
    "utils",
    "core",
    "model",
    "lang",
    "lang2",
    "cli",
    "abi",
]
exclude = [
    "examples/",
    "cli/template/",
]

[profile.release]
panic = "abort"
lto = true
